CREATE TABLE `blog_posts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(255) NOT NULL,
	`title_tw` varchar(255) NOT NULL,
	`title_jp` varchar(255),
	`title_my` varchar(255),
	`excerpt_tw` text,
	`excerpt_jp` text,
	`excerpt_my` text,
	`content_tw` longtext NOT NULL,
	`content_jp` longtext,
	`content_my` longtext,
	`category` varchar(50),
	`tags` json,
	`featured_image_url` varchar(500),
	`author` varchar(100) DEFAULT 'Bert Wang',
	`seo_keywords_tw` varchar(255),
	`seo_keywords_jp` varchar(255),
	`seo_keywords_my` varchar(255),
	`is_published` boolean DEFAULT true,
	`published_at` timestamp DEFAULT CURRENT_TIMESTAMP,
	`view_count` int DEFAULT 0,
	`created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
	`updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `blog_posts_id` PRIMARY KEY(`id`),
	CONSTRAINT `blog_posts_slug_unique` UNIQUE(`slug`)
);
--> statement-breakpoint
CREATE TABLE `case_studies` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(255) NOT NULL,
	`title_tw` varchar(255) NOT NULL,
	`title_jp` varchar(255),
	`title_my` varchar(255),
	`description_tw` text,
	`description_jp` text,
	`description_my` text,
	`challenge_tw` longtext,
	`challenge_jp` longtext,
	`challenge_my` longtext,
	`solution_tw` longtext,
	`solution_jp` longtext,
	`solution_my` longtext,
	`results_tw` longtext,
	`results_jp` longtext,
	`results_my` longtext,
	`client_name` varchar(100),
	`project_category` varchar(50),
	`technologies` json,
	`project_url` varchar(500),
	`completion_date` date,
	`featured_image_url` varchar(500),
	`project_images` json,
	`is_published` boolean DEFAULT true,
	`created_at` timestamp DEFAULT CURRENT_TIMESTAMP,
	`updated_at` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `case_studies_id` PRIMARY KEY(`id`),
	CONSTRAINT `case_studies_slug_unique` UNIQUE(`slug`)
);
